"""Nice exercise, it took some time"""
class Node:
    def __init__(self,state,parent):
        self.state=state
        self.parent=parent

class StackFrontier:
    def __init__(self):
        self.frontier=[]
    def add(self,node):
        self.frontier.append(node)
    def remove(self):
        if self.empty:
            raise Exception("Empty")
        node=self.frontier[-1]
        self.frontier=self.frontier[:-1]
        return node
    @property
    def empty(self):
        return len(self.frontier)==0 #If statement is right it will return True
    @property
    def frontierdata(self):
        return [n.state for n in self.frontier]

class QueueFrontier(StackFrontier):
    def remove(self):
        if self.empty:
            raise Exception("Empty")
        node=self.frontier[0]
        self.frontier=self.frontier[1:]
        return node
    

def main():
    """Graph Maze Generated By ChatGPT"""
    maze={"S":["A","B"],
           "A":["S","C","D"],
           "B":["S","E"],
           "C":["A","F"],
           "D":["A","G"],
           "E":["B","H"],
           "F":["C","T"],
           "G":["D","T"],
           "H":["E"],
           "T":["F","G"]
           }
    start,end=get_points(maze)
    if start==None or end==None:
        return None
    print("\nStarting With DFS")
    dfs(start,end,maze)
    print("\nStarting With BFS")
    bfs(start,end,maze)
    
def get_points(maze):
    print_graph()
    start,end=input("Start and End Points:").upper().split()
    if check_points(start,end,maze):
        return start,end
    else:
        return None,None

def print_graph():
    print("-----GRAPH-----")
    print("        S")
    print("       / \\")
    print("      A   B")
    print("     / \\   \\")
    print("    C   D   E")
    print("    |   |   |")
    print("    F   G   H")
    print("     \\ /")
    print("      T")

def check_points(start,end,maze):
    if start==end:
        print("Start and End Point Is Same")
        return False
    check=0 
    for name in maze:
        if start==name or end==name:
            check+=1
    if check==2:
        return True
    else:
        print("Use Nodes That In The Graph")
        return False
    
def dfs(start,end,maze):
    root=Node(start,None)#Initial Point
    sf=StackFrontier()
    sf.add(root)
    wrong_paths=[]
    visited=[]
    while True:
        if sf.empty:
            raise Exception("Empty Frontier")
        current=sf.remove()
        if current.state==end:
            while current.parent!=None:
                print(current.state,end="<-")
                current=current.parent
            print(current.state)
            print("Took:",len(visited)+1,"cells. Including root")# +1 In order to get every cell
            print("Wrong Paths:",end="")
            for i in wrong_paths:
                for j in i:
                    print(j,end="")
                print("   ",end="")
            return None
        path=0
        for next in maze[current.state]:
            if next not in visited and next not in sf.frontierdata:
                child=Node(next,current)
                sf.add(child)
                path+=1
        visited.append(current.state)
        if path==0:
            wpath=[]
            while current.parent!=None:
                wpath.append(f"{current.state}<-")
                current=current.parent
            if current.parent==None:
                wpath.append(current.state)
                wrong_paths.append(wpath)

def bfs(start,end,maze):
    root=Node(start,None)#Initial Point
    sf=QueueFrontier()
    sf.add(root)
    wrong_paths=[]
    visited=[]
    while True:
        if sf.empty:
            raise Exception("Empty Frontier")
        current=sf.remove()
        if current.state==end:
            while current.parent!=None:
                print(current.state,end="<-")
                current=current.parent
            print(current.state)
            print("Took:",len(visited)+1,"cells. Including root")# +1 In order to get every cell
            print("Wrong Paths:",end="")
            for i in wrong_paths:
                for j in i:
                    print(j,end="")
                print("   ",end="")
            return None
        path=0
        for next in maze[current.state]:
            if next not in visited and next not in sf.frontierdata:
                child=Node(next,current)
                sf.add(child)
                path+=1
        visited.append(current.state)
        if path==0:
            wpath=[]
            while current.parent!=None:
                wpath.append(f"{current.state}<-")
                current=current.parent
            if current.parent==None:
                wpath.append(current.state)
                wrong_paths.append(wpath)

if __name__=="__main__":
    main()

